# workflow name
name: firstworkflow

# Define when this workflow should be executed "on" key is used for that, it is a reserved key which github actions will look for"
on:
  # After "on" keyword define the event or events that should trigger this workflow to run
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

# We need to define job or jobs
jobs:
  # Define a single job with its name "firstaction", naming is totally up to us
  firstaction:
    # Define where our job will run ( like which environment )
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
